import os
import glob
import json

class SEOAgent:
    def __init__(self, web_dir="web", products_dir="products/generated_outputs"):
        self.web_dir = web_dir
        self.products_dir = products_dir

    def find_latest_assets(self):
        product_files = glob.glob(os.path.join(self.products_dir, "*.json"))
        web_files = glob.glob(os.path.join(self.web_dir, "*.html"))
        if not product_files or not web_files:
            return None, None
        return max(product_files, key=os.path.getctime), max(web_files, key=os.path.getctime)

    def optimize_page_seo(self):
        """
        حقن وسوم الـ SEO وتحسين محركات البحث داخل صفحة البيع أوتوماتيكياً
        """
        print("🔍 SEO Agent: Optimizing sales page for global Google search rankings...")
        
        prod_file, web_file = self.find_latest_assets()
        if not prod_file or not web_file:
            print("❌ SEO Agent Error: Assets not found.")
            return False

        with open(prod_file, "r", encoding="utf-8") as f:
            product = json.load(f)

        with open(web_file, "r", encoding="utf-8") as f:
            html_content = f.read()

        # توليد بيانات الـ SEO الاحترافية
        seo_title = f"{product['title']} | Best Notion Template for Freelancers"
        seo_description = f"Supercharge your workflow with {product['title']}. Perfect for {product['target_audience']}. Get instant access now for just ${product['price_usd']}."
        seo_keywords = "Notion template, freelancer crm, productivity dashboard, digital products, solo entrepreneur tools"

        # حقن وسوم الـ SEO في رأس الصفحة (داخل الـ <head>)
        seo_tags = f"""
    <!-- SEO Meta Tags Generated by SEO Agent -->
    <title>{seo_title}</title>
    <meta name="description" content="{seo_description}">
    <meta name="keywords" content="{seo_keywords}">
    <meta name="robots" content="index, follow">
"""
        # استبدال العنوان القديم أو إضافته
        if "<head>" in html_content:
            html_content = html_content.replace("<head>", f"<head>\n{seo_tags}")
            with open(web_file, "w", encoding="utf-8") as f:
                f.write(html_content)

        print(f"✅ SEO Agent: Successfully injected high-ranking SEO tags into {os.path.basename(web_file)}")
        return True

if __name__ == "__main__":
    agent = SEOAgent()
    agent.optimize_page_seo()